In [1]:
#list 인덱싱
a = [1.0, 2.0, 3.0]

In [2]:
a[0]

1.0

In [3]:
a[2] = 3.0
a

[1.0, 2.0, 3.0]

텐서 만들어보기

In [4]:
import torch

In [5]:
#크기가 3인 1차원 텐서를 만들고 값을 1로 채우기
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [6]:
a[1]

tensor(1.)

In [7]:
float(a[1])

1.0

In [8]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [9]:
#.zeors를 사용하면 쉽게 원하는 크기의 배열을 얻음
points = torch.zeros(6)
points[0] = 4.0 #그러고 나서 원하는 값으로 모든 0을 덮어씀.
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0
points

tensor([4., 1., 5., 3., 2., 1.])

In [10]:
#생성자에 파이썬 리스트를 넘겨도 된다.
points = torch.tensor([4.0,1.0,5.0,3.0,2.0,1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [11]:
#첫 번째 점의 좌표를 읽으려면 다음과 같이 한다.
float(points[0]), float(points[1])

(4.0, 1.0)

In [12]:
#하지만 좌표 대신 2차원 좌표를 바로 인덱싱하는게 더 실용적이니 2차원 텐서를 사용하자.
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [13]:
#이번에는 리스트의 리스트를 생성자로 넘겨주고 텐서의 차원을 살펴보자.
points.shape

torch.Size([3, 2])

In [14]:
#텐서 초기화를 위해 차원별 크기 정보를 튜플로 만들어 zeros나 ones로 넘겨줄 수도 있다.
points = torch.zeros(3,2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [15]:
#두 개의 인덱스로 텐서 내 요소를 개별적으로 접근할 수 있다.
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [16]:
points[0,1]

tensor(1.)

In [17]:
points[0]

tensor([4., 1.])

텐서 인덱싱

In [18]:
some_list = list(range(6))
some_list[:]     # 리스트의 모든 요소
some_list[1:4]   # 1번 인데스부터 4번 인덱스 전까지
some_list[1:]    # 1번 인덱스에 있는 요소부터 끝까지
some_list[:4]    # 1번 ~ 4번 전
some_list[:-1]   # 리스트의 첫 번째 요소부터 마지막 요소 바로 앞까지
some_list[1:4:2] # 1번 ~ 4번 전까지 두 단계씩 건너 뛰면서

[1, 3]

In [19]:
#파이썬과 동일한 표기법, 텐서도 마찬가지
points[1:] #첫 번째 이후 모든 행에 대해. 암묵적으로 모든 열이 포함됨
points[1:, :] #첫 번째 이후 모든 행에 대해. 명시적으로 모든 열이 포함된
points[1:, 0] #첫 번째 이후 모든 행에 대해 첫 번째 열만 포함됨
points[None] #길이가 1인 차원을 추가함. unsueeze와 동일함

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

## 텐서의 dtype 속성 관리

In [20]:
#숫자 타입이 올바르게 지정된 텐서를 하나 할당할 때에는 생성자에 dtype 인자를 정확하게 전달해야 한다. 예를들면
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1,2], [3,4]], dtype=torch.short)

In [21]:
#어떤 텐서가 가진 dtype을 알고 싶다면 다음과 같이 대응하는 속성을 읽어보면 된다.
short_points.dtype

torch.int16

In [22]:
#텐서 생성 함수가 반환하는 텐서의 타입을 대응하는 캐스팅 메소드를 사용해 올바른 타입으로 변환하는 것도 가능하다.
double_points = torch.zeros(10,2 ).double()
short_points = torch.ones(10, 2).short()

In [23]:
double_points.dtype

torch.float64

In [24]:
#혹은 to 메소드를 사용하면 더 편하다.
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.zeros(10, 2).to(torch.short)

In [25]:
short_points.dtype

torch.int16

In [26]:
#to 메소드는 변환이 필요한 경우에만 진행한다. float 같은 dtype 이름을 사용한 캐스팅은 to를 사용한 것보다 짧게 쓸 수 있지만 to 메소드는 타입 외에도 추가적인 인자를 지정할 수 있다.

In [27]:
#여러 탑입을 가진 입력들이 연산을 거치며 서로 섞일 때 자동으로 제일 큰 타입으로 만들어진다.
#따라서 만약 32비트 연산을 원한다면 입력 타입 중 가장 큰 것이 32비트인지 확인해야 한다.

points_64 = torch.rand(5, dtype=torch.double) #rand는 텐서 요소를 0과 1사이 임의의 수로 초기화함.
points_short = points_64.to(torch.short)
points_64 * points_short

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

## 텐서 API

In [28]:
#텐서끼리의 연산 대부분은 torch 모듈에 있고 대부분이 텐서 객체에 대해 메소드처럼 호출할 수 있다. 예를 들어 앞에서 본 transpose 함수도 torch 모듈로 호출한다.
a = torch.ones(3,2)
a_t = torch.transpose(a, 0, 1)

In [29]:
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [30]:
#동일코드
a = torch.ones(3,2)
a_t = a.transpose(0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

## 저장 공간 인덱싱

In [31]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

<ipython-input-31-8575ff47c9e0>:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points.storage()
/usr/local/lib/python3.10/dist-packages/IPython/lib/pretty.py:700: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  output = repr(obj)
/usr/local/lib/python3.10/dist-packages/torch/storage.py:645: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [32]:
#이 텐서는 세 개의 행과 두 개의 열로 이루어져 있지만 실제로는 크기가 6인 배열 공간일 뿐이다.
#텐서는 주어진 차원 쌍이 실제로 어느 공간에 해당하는지를 알 뿐이다.
#따라서 텐서를 거치지 않고 저장 곤간을 다음과 같이 직접 접근할 수도 있다.

points_storage = points.storage()
points_storage[0]

<ipython-input-32-69707b2e6a0e>:5: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points_storage = points.storage()
<ipython-input-32-69707b2e6a0e>:6: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points_storage[0]


4.0

In [33]:
#차원에 무관하게 실제 저장 곤간 레이아웃은 1차원이다.
points.storage()[1]

<ipython-input-33-b47fcd2424a2>:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points.storage()[1]


1.0

In [34]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
points_storage[0] = 2.0

points

<ipython-input-34-6950be4dae48>:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points_storage = points.storage()
<ipython-input-34-6950be4dae48>:3: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points_storage[0] = 2.0


tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [35]:
points.storage()

<ipython-input-35-2c8c1a84fa09>:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points.storage()


 2.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

## 저장된 값을 수정하기: 텐서 내부 연산

In [36]:
#Tensor 객체에 대해서만 동작하는 몇 가지 연산을 더 알아보자
#이 연산은 zero_처럼 _로 끝나는데 연산의 결과로 새 텐서가 넘어오는 대신 기존 텐서의 내용이 바뀐다.
#예를 들어 zero_ 메소드는 입력된 텐서의 모든 요소를 0으로 바꾼다. 밑줄로 끝나지 않는 모든 메소드들은 원래 텐서는 그대로 두고 새로운 텐서를 만들어 넘겨준다.

a = torch.ones(3,2)

In [37]:
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

## 다른 텐서의 저장 곤간에 대한 뷰 만들기

In [38]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point.storage_offset()

2

In [39]:
second_point.size()

torch.Size([2])

In [40]:
second_point.shape

torch.Size([2])

In [41]:
points.stride()

(2, 1)

In [42]:
second_point.stride()

(1,)

In [43]:
#2차원 텐서에서 요소 i,j에 접근한다면 저장 공간상으로는 storage_offset + stride[0] * i + stride[1] * j 번째 요소다.

#그리고 중요한 점은 예상대로 새 텐서가 원래의 ponnts 텐서보다 하나 작은 차원을 가지지만 여전히 동일한 저장 공간을 가리키고 있다는 점이다. 때문에 새 텐서를 변경하면 원래의 텐서도 바뀐다.

In [44]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [45]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

## 복사 없이 텐서 전치하기

In [46]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [47]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [48]:
#두 텐서가 같은 공간을 가리키고 있는가?
id(points.untyped_storage()) == id(points_t.untyped_storage())

True

## GPU 에서 텐서 만들기

In [49]:
!nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0


In [50]:
device = torch.device('cuda')

In [52]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')
#points_gpu = points.to(device='cuda)

In [53]:
points_gpu = points.to(device='cuda:0')

In [54]:
points = 2*points
points_gpu = 2 * points.to(device='cuda')

## NumPy 호환

In [55]:
points = torch.ones(3,4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)