In [1]:
#list 인덱싱
a = [1.0, 2.0, 3.0]

In [2]:
a[0]

1.0

In [3]:
a[2] = 3.0
a

[1.0, 2.0, 3.0]

텐서 만들어보기

In [4]:
import torch

In [8]:
#크기가 3인 1차원 텐서를 만들고 값을 1로 채우기
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [9]:
a[1]

tensor(1.)

In [11]:
float(a[1])

1.0

In [12]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [16]:
#.zeors를 사용하면 쉽게 원하는 크기의 배열을 얻음
points = torch.zeros(6)
points[0] = 4.0 #그러고 나서 원하는 값으로 모든 0을 덮어씀.
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0
points

tensor([4., 1., 5., 3., 2., 1.])

In [17]:
#생성자에 파이썬 리스트를 넘겨도 된다.
points = torch.tensor([4.0,1.0,5.0,3.0,2.0,1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [18]:
#첫 번째 점의 좌표를 읽으려면 다음과 같이 한다.
float(points[0]), float(points[1])

(4.0, 1.0)

In [20]:
#하지만 좌표 대신 2차원 좌표를 바로 인덱싱하는게 더 실용적이니 2차원 텐서를 사용하자.
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [21]:
#이번에는 리스트의 리스트를 생성자로 넘겨주고 텐서의 차원을 살펴보자.
points.shape

torch.Size([3, 2])

In [22]:
#텐서 초기화를 위해 차원별 크기 정보를 튜플로 만들어 zeros나 ones로 넘겨줄 수도 있다.
points = torch.zeros(3,2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [23]:
#두 개의 인덱스로 텐서 내 요소를 개별적으로 접근할 수 있다.
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [24]:
points[0,1]

tensor(1.)

In [29]:
points[0]

tensor([4., 1.])

텐서 인덱싱

In [30]:
some_list = list(range(6))
some_list[:]     # 리스트의 모든 요소
some_list[1:4]   # 1번 인데스부터 4번 인덱스 전까지
some_list[1:]    # 1번 인덱스에 있는 요소부터 끝까지
some_list[:4]    # 1번 ~ 4번 전
some_list[:-1]   # 리스트의 첫 번째 요소부터 마지막 요소 바로 앞까지
some_list[1:4:2] # 1번 ~ 4번 전까지 두 단계씩 건너 뛰면서

[1, 3]

In [31]:
#파이썬과 동일한 표기법, 텐서도 마찬가지
points[1:] #첫 번째 이후 모든 행에 대해. 암묵적으로 모든 열이 포함됨
points[1:, :] #첫 번째 이후 모든 행에 대해. 명시적으로 모든 열이 포함된
points[1:, 0] #첫 번째 이후 모든 행에 대해 첫 번째 열만 포함됨
points[None] #길이가 1인 차원을 추가함. unsueeze와 동일함

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])